est-ios-3nd-team4/Meditory

- Meditory/Meditory/Features/Recommend/RecommendView.swift
> chore: features 디렉토리 구성

- Meditory/Meditory/Data/ExtraInfo.swift
- Meditory/Meditory/MeditoryApp.swift
- Meditory/Meditory/Models/Routine/Routine.swift
- Meditory/Meditory/Models/Routine/RoutineRecord.swift
- Meditory/Meditory/Models/Routine/RoutineTime.swift
- Meditory/Meditory/Models/User/User.swift
- Meditory/Meditory/Models/User/UserAllergy.swift
- Meditory/Meditory/Models/User/UserExtraInfo.swift
- Meditory/Meditory/Models/User/UserProfile.swift
- Meditory/Meditory/Models/User/UserStatus.swift
- Meditory/Meditory/SettingsView.swift
- User, User의 하위 테이블 생성
- ExtraInfo(질병관련 Data) 추가
- Routine(약, 영양제 복용주기) 관련 테이블 추가
어떤 변경 사항이 있나요?
> Scrum-13 데이터 모델링

- Meditory/Meditory/Data/ExtraInfo.swift
- Meditory/Meditory/Models/Nutrient/Nutrient.swift
- Meditory/Meditory/Models/Nutrient/NutrientRecommendation.swift
- Meditory/Meditory/Models/Nutrient/Scrap.swift
- 약 영양제 관련 모델 추가
- 질병 알러지 데이터 추가
어떤 변경 사항이 있나요?
> Feature/scrum 13 데이터 모델링

- Meditory/Meditory/Features/Home/View/HomeView.swift
영양제 버튼 선택 시 토글 안 되는 문제 해결
어떤 변경 사항이 있나요?
> fix/SCRUM-69 영양제 버튼 선택 시 토글 안 되는 문제 해결

- Meditory/Meditory/Features/Common/CalendarBackgroundView.swift
- CalendarBackgroundView의 background가 all로 안 채워지는 부분 수정 및 상단에만 cornerradius 적용
- 폰트 변경 및 패딩 변경
어떤 변경 사항이 있나요?
> SCRUM-70 CalendarBackgroundView 수정

- Meditory/Meditory/Extension/Color+Extension.swift
- Meditory/Meditory/Features/Common/CalendarBackgroundView.swift
- Meditory/Meditory/Features/Common/CircleCheck.swift
- Meditory/Meditory/Features/Home/View/Components/CircularProgressView.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/View/TodayHealthView.swift
- Meditory/Meditory/Features/Home/ViewModel/TodayHealthViewModel.swift
- 다크 모드 대응 
- CheckCircle 컴포넌트 추가
- 프롬프트 수정(Example에 "" 를 넣었더니 그대로 출력해주길래 "" 제거)
어떤 변경 사항이 있나요?
> Feat/SCRUM-72 다크모드 대응

- Meditory/Meditory/Features/Home/View/Components/CircularProgressView.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/View/TodayHealthView.swift
- Chart 애니메이션 시 원과 그래프의 노선 애니메이션 경로가 달라지는 문제 해결
- 100%가 되었을 시 글자 크기가 오버 되는 문제 해결
어떤 변경 사항이 있나요?
> feat/SCRUM-74 Chart 수정

- Meditory/Meditory/Features/Common/CalendarBackgroundView.swift
- Meditory/Meditory/Features/Home/View/Components/CircularProgressView.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
UI: 요일 점 표시 제거 및 차트 중앙 정렬/텍스트 크기 조정
- 선택 날짜 점 표시 UI 제거
- 차트 내 숫자 중앙 정렬
- 차트 텍스트 크기 조정
어떤 변경 사항이 있나요?
> feat/SCRUM-78 UI 추가 수정

- Meditory/Meditory/Data/ExtraInfo.swift
- Meditory/Meditory/Data/Store/UserStore.swift
- Meditory/Meditory/Features/Home/ViewModel/TodayHealthViewModel.swift
- Meditory/Meditory/MeditoryApp.swift
- Meditory/Meditory/Models/User/UserExtraInfo.swift
- Meditory/MeditoryTests/SwiftDataTest/UserTest.swift
- UserExtraInfo, ExtraInfo 관련 부분에 대한  전체적인 구조변경
- User 부분 정식 테스트코드 작성
어떤 변경 사항이 있나요?
> Feat/scrum-92 user extra info extra info 관련 테이블 구조변경2

- Meditory/Meditory/Models/Routine/Routine.swift
- Routine 의 요일 모델 배열로 변경. 기존에는 그냥 Int 라 여러개 저장 불가능했음
- 
어떤 변경 사항이 있나요?
> feat: Routine 의 요일 모델 배열로 변경

- Meditory/Meditory/Data/Store/RoutineStore.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Routine 삭제기능 생성, cycle 오류 수정(요일배열추가로 인한 오류)
어떤 변경 사항이 있나요?
> feat: Routine 삭제기능 생성, cycle 오류 수정

- Meditory/MeditoryTests/SwiftDataTest/RoutineTest.swift
- RoutineTest 테스트코드 작성
어떤 변경 사항이 있나요?
> test: RoutineTest 테스트코드 작성

- Meditory/Meditory/Features/Recommend/View/AnalysisView.swift
- Meditory/Meditory/Features/Recommend/View/CardView.swift
- Meditory/Meditory/Features/Recommend/View/NutrientCardView.swift
- Meditory/Meditory/Features/Recommend/View/NutrientDetailSectionView.swift
- Meditory/Meditory/Features/Recommend/View/ProductCardView.swift
- Meditory/Meditory/Features/Recommend/View/RecommendNutrientsView.swift
- Meditory/Meditory/Features/Recommend/View/RecommendView.swift
- Meditory/Meditory/Features/Recommend/View/ScoreView.swift
- Meditory/Meditory/Features/Recommend/View/ScoredetailView.swift
- Meditory/Meditory/Features/Recommend/View/ScrapView.swift
fix/SCRUM-113-스크랩화면 UI수정
fix/SCRUM-115-spacing,cornerRadius코드수정
어떤 변경 사항이 있나요?
> feat/SCRUM-110-상세보기화면 UI보완

- Meditory/Meditory/Features/SupplementDetail/Components/DeleteAlertView.swift
- Meditory/Meditory/Features/SupplementDetail/Components/GuideCard.swift
- Meditory/Meditory/Features/SupplementDetail/Components/HeaderCard.swift
- Meditory/Meditory/Features/SupplementDetail/Components/ScheduleDisplayRow.swift
- Meditory/Meditory/Features/SupplementDetail/Components/SchedulePanel.swift
- Meditory/Meditory/Features/SupplementDetail/Components/SplitScheduleCard.swift
- Meditory/Meditory/Features/SupplementDetail/Model/SupplementDetailDTO.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Meditory/Meditory/Features/SupplementDetail/ViewModel/SupplementDetailViewModel.swift
영양제 상세 화면 UI 구현
어떤 변경 사항이 있나요?
> feat: 영양제 상세 화면 UI 구현

- Meditory/Meditory/Features/Common/FlowLayout.swift
- Meditory/Meditory/Features/Recommend/View/RecommendView.swift
- Meditory/Meditory/Features/Recommend/View/SearchView.swift
영양제추천 검색화면 UI 구현, FlowLayout 공통코드 생성
어떤 변경 사항이 있나요?
> 영양제추천 검색화면 UI 구현, FlowLayout 공통코드 생성  Scrum-121 

- Meditory/Meditory/Features/SupplementDetail/Components/SchedulePanel.swift
- Meditory/Meditory/Features/SupplementDetail/Components/SplitScheduleCard.swift
- Meditory/Meditory/Features/SupplementDetail/Components/SupplementGuideCard.swift
- Meditory/Meditory/Features/SupplementDetail/Components/SupplementHeaderCard.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Components 겹칠 수 있는 파일명에 Supplement 추가
- SchedulePanel 여백 조정 및 .top 정렬 맞춤
- UI:  그림자 추가
어떤 변경 사항이 있나요?
> feat: SupplementDetail UI 수정 및 View 이름 변경 (SCRUM-133)

- Meditory/Meditory/Features/Common/FlowLayoutLineLimit.swift
- Meditory/Meditory/Features/Recommend/View/SearchView.swift
FlowLayout2 이름변경, 여백수치 상수화 (SCRUM-146)
어떤 변경 사항이 있나요?
> chore: FlowLayout2 이름변경, 여백수치 상수화 (SCRUM-146)

- Meditory/Meditory/Extension/Date+Extension.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/SupplementAI/SupplementInfoPrompt.swift
- Meditory/Meditory/Features/SupplementAI/SupplementRoutineAIViewModel.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Meditory/Meditory/Features/SupplementDetail/ViewModel/SupplementDetailViewModel.swift
- Meditory/Meditory/Network/DTO/Supplement/SupplementDTO.swift
- Meditory/Meditory/Persistence/Stores/RoutineStore+AIRecommendation.swift
- 영양제 관련 프롬프트 작성 및 DTO, Service 파일 추가
- 관련 Routine Extension 추가
- Home과 SupplementDetail 쪽에서 Routine 넘기고 받는 방식으로 수정
어떤 변경 사항이 있나요?
- [] 파일 혹은 폴더 삭제
> feat: 영양제 관련 프롬프트 작성(SCRUM-141)

- Meditory/Meditory/Features/Onboarding/Components/TitleView.swift
- Meditory/Meditory/Features/Onboarding/Model/FormField.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingAllergyView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingBasicInfoView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingConcernView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingDiseaseView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
뷰모델의 재사용성과 무게를 가볍기 위한 리팩토링
불필요 애니메이션 제거
어떤 변경 사항이 있나요?
> refactor: 온보딩뷰 전체적으로 리팩토링(SCRUM-174)

- Meditory/Meditory/Extension/DateFormatter+Extension.swift
- Meditory/Meditory/Features/Onboarding/Components/TitleView.swift
- Meditory/Meditory/Features/Onboarding/Model/Prompt.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingAllergyView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingConcernView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingDiseaseView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
뷰모델 리팩토링
새로운 온보딩뷰 카운팅 피드백 레이블 추가
어떤 변경 사항이 있나요?
> refacor: 뷰모델 기능 리팩토링 (SCRUM-168)

- Meditory/Meditory/Features/Setting/View/SettingView.swift
- Meditory/Meditory/Persistence/DataController.swift
- Meditory/Meditory/Persistence/Models/Meal/Convert/MealConvert.swift
- Meditory/Meditory/Persistence/Models/Meal/Meal.swift
- Meditory/MeditoryTests/PromptTest/ScheduleAIPromptTests.swift
- Meditory/MeditoryTests/SwiftDataTest/MealModelConversionTest.swift
- 식단 db모델링 재작업
- 식단 변경으로 인한 테스트코드 수정 
- UserStore 변경으로 인한 ScheduleAIPromptTests 테스트코드 수정 
어떤 변경 사항이 있나요?
> Feat/scrum 185 식단 db모델링 재작업

- Meditory/Meditory/Features/SupplementDetail/Components/Guide/SupplementGuideCard.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Meditory/Meditory/Features/SupplementDetail/ViewModel/SupplementDetailViewModel.swift
- 복용 스케줄 아래에 메모를 추가했습니다.
- SupplementGuideCard 개선
- GuideType에 title, icon, tint 계산 프로퍼티를 추가하여, 간결하게 관리하도록 개선했습니다.
- 루틴 삭제 시 뷰 크래시 버그 수정
- 삭제된 객체를 참조하면서 발생하던 크래시를 해결했습니다. routine을 옵셔널로 관리하고, 삭제 시 nil 처리 후 dismiss()로 안전하게 종료되도록 수정했습니다.
어떤 변경 사항이 있나요?
> 영양제 상세화면 메모 추가 및 삭제 로직 수정(SCRUM-186)

- Meditory/Meditory/Features/Setting/View/SettingView.swift
- Meditory/Meditory/Features/Setting/ViewModel/SettingViewModel.swift
- Meditory/Meditory/Persistence/ExtraInfo.swift
- Meditory/Meditory/Persistence/Models/Setting/Setting.swift
- Meditory/Meditory/Persistence/Models/User/User.swift
- Meditory/Meditory/Persistence/Models/User/UserExtraInfo.swift
- Meditory/Meditory/Persistence/Models/User/UserLifeStyle.swift
- Meditory/Meditory/Persistence/Models/User/UserProfile.swift
- Meditory/Meditory/Persistence/Models/User/UserStatus.swift
- Meditory/Meditory/Persistence/Stores/SettingStore.swift
- @unchecked 제거 (위험)
- Setting 관련코드들에 @ModelActor 적용
어떤 변경 사항이 있나요?
> Feat/scrum 188 model actor 변경 setting

- Meditory/Meditory/Features/Onboarding/Components/RowItemCell.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
성별이 남성일 경우 옵션이 보이지 않도록 수정
리스트의 섭타이틀의 사이즈를 변경할 수 있도록 수정
어떤 변경 사항이 있나요?
> design: 온보딩 성별 UI 수정 (SCRUM-192)

- Meditory/Meditory/Features/AddIntake/View/AddIntakeSelectorPadView.swift
- Meditory/Meditory/Features/AddIntake/View/AddIntakeSelectorView.swift
- Meditory/Meditory/Features/AddSupplement/View/AddSupplementView.swift
- Meditory/Meditory/Features/MainTab/Components/AddIntakeButton.swift
- Meditory/Meditory/Features/MainTab/CustomTabView.swift
- Meditory/Meditory/Features/MainTab/MainTabView.swift
- MainTabView 와 AddIntakeSelectorView의 Subview 분리 작업을 하였습니다.
-  iPad 영양제 및 식단 추가 버튼을 구현하였습니다. (AddIntakeSelectorPadView)
- 추가 버튼 애니메이션을 구현하였습니다.
- ColorScheme에 대응하여 색상을 처리하였습니다.
<div align="center">
https://github.com/user-attachments/assets/6d57ecf5-f826-48aa-81ae-f19bb8e20396
</div>
어떤 변경 사항이 있나요?
> iPad 영양제 및 식단 추가 버튼 구현 (SCRUM-190)

- Meditory/Meditory/Features/AddSupplement/View/AddSupplementView.swift
- Meditory/Meditory/Features/AddSupplement/ViewModel/LifestyleTimeViewModel.swift
- Meditory/Meditory/Features/MainTab/MainTabView.swift
- Meditory/Meditory/Features/SupplementDetail/Components/Schedule/SchedulePanel.swift
- Meditory/Meditory/Persistence/Stores/UserLifeStyleStore.swift
- ModelActor작업_UserLifeStyleStore
- UserLifeStyleStore 변경에따른 영향을 받는 파일들 변경
어떤 변경 사항이 있나요?
> Feat/scrum 196 user life style store 모델액터화

- Meditory/Meditory/Features/AddSupplement/View/AIRecommendedScheduleView.swift
- Meditory/Meditory/Features/AddSupplement/View/AddSupplementView.swift
- Meditory/Meditory/Features/AddSupplement/View/SupplementInfoView.swift
- Meditory/Meditory/Features/AddSupplement/ViewModel/AddSupplementViewModel.swift
- Meditory/Meditory/Features/AddSupplement/ViewModel/SupplementRoutineAIViewModel.swift
- Meditory/Meditory/Features/Home/Model/HomeRoutineManager.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/ViewModel/HomeViewModel.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Meditory/Meditory/Features/SupplementDetail/ViewModel/SupplementDetailViewModel.swift
- Meditory/Meditory/Persistence/Stores/RoutineStore.swift
- RoutineStore 관련 MainActor화 작업 (SCRUM-198)
어떤 변경 사항이 있나요?
> feat: RoutineStore 관련 MainActor화 작업 (SCRUM-198)

- Meditory/Meditory/Features/CalendarBackground/Components/CalendarWeeklyHeader.swift
- Meditory/Meditory/Features/CalendarBackground/Components/DayCell/SheetDayCell.swift
- Meditory/Meditory/Features/CalendarBackground/Components/Header/CalendarMonthHeader.swift
- Meditory/Meditory/Features/CalendarBackground/Components/Header/CalendarWeekdayHeader.swift
- Meditory/Meditory/Features/Home/Components/CircularProgressView.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/ViewModel/TodayHealthViewModel.swift
- HomeView IPad 대응했습니다.(HStack 반으로 하려고 했는데 여백이 너무 많이 남아 추후 반영할게요)
- MainActor.run을 추가하였습니다.
어떤 변경 사항이 있나요?
> HomeView IPad 대응(SCRUM-138)

- Meditory/Meditory/Persistence/Stores/MealStore.swift
- Meditory/Meditory/Persistence/Stores/RoutineStore+AIRecommendation.swift
- RoutineStore+AI 관련 extension 모델액터방식에 맞게 변환
- MealStore 모델액터방식으로 변환
어떤 변경 사항이 있나요?
> RoutineStore+AI 수정, MealStore @ModelActor 화 (SCRUM-200)

- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
- Meditory/MeditoryTests/SwiftDataTest/OnboardingUnitTest.swift
온보딩뷰의 3가지 유닛테스트 추가
1.입력필드가 유효한지
2.모든 입력필드가 유효하여야 다음 버튼이 활성화 되는지
3.최종 가입후 특정 성별의 옵션이 담겨있는지
어떤 변경 사항이 있나요?
> test: 온보딩 유닛테스트(SCRUM-201)

- Meditory/Meditory/Features/Onboarding/View/OnboardingBasicInfoView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
- Meditory/Meditory/Persistence/Stores/RoutineStore.swift
- Meditory/Meditory/Persistence/Stores/UserLifeStyleStore.swift
- Meditory/Meditory/Persistence/Stores/UserStore.swift
- Meditory/MeditoryTests/PromptTest/ScheduleAIPromptTests.swift
- Meditory/MeditoryTests/SwiftDataTest/MealModelConversionTest.swift
- Meditory/MeditoryTests/SwiftDataTest/OnboardingUnitTest.swift
- Meditory/MeditoryTests/SwiftDataTest/RoutineTest.swift
- Meditory/MeditoryTests/SwiftDataTest/UserLifeStyleTest.swift
- Meditory/MeditoryTests/SwiftDataTest/UserTest.swift
- 테스트코드 수정, user관련 메서드 수정
- User 정보를 불러올 때 User객체가 아닌 UserID를 통해 불러오는 방식으로 변경
- User계열 스토어 변경으로 인한 테스트코드 수정
어떤 변경 사항이 있나요?
> 테스트코드 수정, user관련 메서드 수정 (SCRUM-202)

- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/MeditoryTests/SwiftDataTest/OnboardingUnitTest.swift
유저 초기 진입시 여성옵션 미노출 
어떤 변경 사항이 있나요?
> feat/SCRUM-204 온보딩 성별 UI피드백 반영

- Meditory/Meditory/Features/AddSupplement/ViewModel/SupplementRoutineAIViewModel.swift
- Meditory/MeditoryTests/PromptTest/ScheduleAIPromptTests.swift
ScheduleAIPromptTests, 관련함수 수정 (SCRUM-205)
- 관련함수(makePrompt) 가 context 를 인자로 받아놓고 전역 context 를 써서 생긴 문제
어떤 변경 사항이 있나요?
> ScheduleAIPromptTests, 관련함수 수정 (SCRUM-205)

- Meditory/Meditory/Features/Home/Model/HomeRoutineManager.swift
- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/View/TodayHealthView.swift
- Meditory/Meditory/Features/Home/ViewModel/HomeViewModel.swift
- Meditory/Meditory/Features/Home/ViewModel/TodayHealthViewModel.swift
- Meditory/MeditoryTests/HomeViewTest/TodayHealthViewModelTests.swift
- RoutineStore 수정 이후 동일 시간에 다른 영양제가 함께 체크되는 문제가 있어 수정했습니다.
- 앱 실행 시 한 번만 네트워크 호출을 하게 하였습니다. 동일 세션 내 재호출은 캐시를 활용하게 하였습니다.
- 프롬프트를 수정하여 간결하게 150자 정도 나타나게 하였습니다.
- TodayHealthViewModelTests를 추가하여 한번만 호출되는지 확인하였습니다.
어떤 변경 사항이 있나요?
> Home & 오늘의 건강 상식 호출 수정, 테스트 코드 작성(SCRUM-203)

- Meditory/Meditory/Features/MainTab/DefaultTabView.swift
- 아이패드 세팅화면 안나오는 버그 수정
어떤 변경 사항이 있나요?
> 아이패드 세팅화면 안나오는 버그 수정 (SCRUM-209)

- Meditory/Meditory/Features/Home/View/HomeView.swift
- Meditory/Meditory/Features/Home/ViewModel/HomeViewModel.swift
- Meditory/MeditoryTests/HomeViewTest/HomeRoutineManagerTests.swift
- Meditory/MeditoryTests/HomeViewTest/HomeViewModelTests.swift
###HomeView
- HomeViewModel Test 코드를 작성하였습니다.
- HomeRoutineManager Test 코드를 작성하였습니다.
- ForEach 문 순회 중 과거 날짜로 갈 시 인덱스가 어긋나는 문제가 발생하여 수정하였습니다.
어떤 변경 사항이 있나요?
> test: HomeView 관련 Test 코드(SCRUM-207)

- Meditory/Meditory/Features/SupplementDetail/Components/Schedule/SchedulePanel.swift
- Meditory/Meditory/Features/SupplementDetail/Components/Schedule/TimeRow.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Routine을 바로 넘길 수 있게 수정하였습니다. 
- 불필요한 top 여백을 제거하였습니다.
- AddSupplement 수정 후 여기 주석 해제하시면 됩니다.(SchedulPanel 55번)
어떤 변경 사항이 있나요?
> 영양제 상세화면 Routine 넘기게 수정(SCRUM-216)

- Meditory/Meditory/Features/Onboarding/Components/TextInputView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
필드에 2글자 이상 입력시 바로 피드백 나오는 것에 딜레이를 추가했습니다
어떤 변경 사항이 있나요?
> bug:온보딩필드 입력유효성 실패 피드백에 디바운스 추가(SCRUM-215)

- Meditory/Meditory/Features/DailyNutrition/Model/MealNutrition.swift
- Meditory/Meditory/Features/DailyNutrition/Model/Prompt/MealNutritionPrompt.swift
- Meditory/Meditory/Features/DailyNutrition/ViewModel/NutritionMainViewModel.swift
- 식단 영양정보 프롬프트를 구현하였습니다.
- NutritionMainViewModel에 요청 코드르 작성하였습니다.
- 프롬프트는 틀만 구현해놨으며 디테일한 요구사항은 직접 수정부탁드립니다.
어떤 변경 사항이 있나요?
> 식단 영양 정보 프롬프트 작성 (SCRUM-222)

- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
- Meditory/MeditoryTests/SwiftDataTest/OnboardingUnitTest.swift
온보딩 뷰모델의 추가 테스트를 구현했습니다
어떤 변경 사항이 있나요?
> 온보딩뷰모델 추가 케이스 테스트 구현(SCRUM-228)

- Meditory/Meditory/Features/AddSupplement/ViewModel/AddSupplementViewModel.swift
- Meditory/Meditory/Features/AddSupplement/ViewModel/SupplementRoutineAIViewModel.swift
- Meditory/Meditory/Features/DailyNutrition/ViewModel/NutritionMainViewModel.swift
- Meditory/Meditory/Network/Client/AlanAPIClient.swift
- AlanAPI 요청 및 응답 현황을 확인하기 위한 print 구문을 추가했습니다.
어떤 변경 사항이 있나요?
> AlanAPI 요청/응답 및 응답 데이터 print 추가 (SCRUM-234)

- Meditory/Meditory/Features/Onboarding/Components/CollectionItemCell.swift
- Meditory/Meditory/Features/Onboarding/Components/ImageWithTitle.swift
- Meditory/Meditory/Features/Onboarding/Components/RowItemCell.swift
아이템 선택시 타이틀이 강조되도록 색을 추가했습니다 (SCRUM-242)
어떤 변경 사항이 있나요?
> 아이템 선택시 강조색(검은색) 변경 (SCRUM-242)

- Meditory/Meditory/Features/IntroduceOnboarding/OnboardingPage.swift
- iPad 온보딩 대응이 가능하게 수정하였습니다.
- 아이폰에서도 PageController와 텍스트 사이의 여백을 늘렸습니다.
어떤 변경 사항이 있나요?
> 온보딩 아이패드 대응(SCRUM-249)

- Meditory/Meditory/Features/Common/PrimaryButton.swift
- Meditory/Meditory/Features/Onboarding/Components/CapsuleShappedText.swift
- Meditory/Meditory/Features/Onboarding/Components/CollectionItemCell.swift
- Meditory/Meditory/Features/Onboarding/Components/ImageWithTitle.swift
- Meditory/Meditory/Features/Onboarding/Components/OnboardingFlowLayoutLineLimit.swift
- Meditory/Meditory/Features/Onboarding/Components/RowItemCell.swift
- Meditory/Meditory/Features/Onboarding/Components/TextInputView.swift
- Meditory/Meditory/Features/Onboarding/Components/TitleView.swift
- Meditory/Meditory/Features/Onboarding/Utility/NoQuickTypeTextField.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingDiseaseView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
아이패드대응 코드들을 추가했습니다
어떤 변경 사항이 있나요?
> 아이패드 대응 (SCRUM-248)

- Meditory/Meditory/Features/AddSupplement/Components/CircleIconButton.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
- Meditory/Meditory/Features/Recommend/View/ScoreView.swift
- Meditory/Meditory/Features/Recommend/View/SearchView.swift
- Meditory/Meditory/Features/SupplementDetail/View/SupplementDetailView.swift
- Meditory/Meditory/Persistence/ExtraInfo.swift
- Meditory/Meditory/Persistence/Models/Routine/Routine.swift
- Meditory/Meditory/Persistence/Models/Setting/Setting.swift
- Meditory/Meditory/Persistence/Models/User/User.swift
- Meditory/Meditory/Persistence/Models/User/UserExtraInfo.swift
- Meditory/Meditory/Persistence/Models/User/UserLifeStyle.swift
- Meditory/Meditory/Persistence/Models/User/UserProfile.swift
- Meditory/Meditory/Persistence/Models/User/UserStatus.swift
빌드시 이슈로 뜨는 것들 해결했습니다.
어떤 변경 사항이 있나요?
> chore: 빌드시 이슈 안내 해결 (SCRUM-254)

- Meditory/Meditory/Features/AddSupplement/View/AddSupplementView.swift
- Meditory/Meditory/Features/Common/NavigationBar/PrimaryNavigationBar.swift
- 아이패드 가로모드 조건이 잘못적용되어 세로모드에서 키보드가 올라갈때 가로모드로 인식되는 버그 수정하였습니다.
- PrimaryNavigationBar 아이패드 대응 조건을 수정하였습니다.
어떤 변경 사항이 있나요?
> iPad 영양제 정보 입력시 셀이 작아지는 버그 수정 (SCRUM-256)

- Meditory/Meditory/Features/Onboarding/Utility/KeyboardObserver.swift
- Meditory/Meditory/Features/Onboarding/Utility/NoQuickTypeTextField.swift
- Meditory/Meditory/Features/Onboarding/Utility/ToggleImageName.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingBasicInfoView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingDiseaseView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
- Meditory/Meditory/Features/Onboarding/ViewModel/OnboardingViewModel.swift
온보딩 코드 순서 재배치 및 주석 추가입니다
어떤 변경 사항이 있나요?
> chore:온보딩 코드 정리 및 주석 추가

- Meditory/Meditory/Features/Notification/NotificationManager.swift
- Meditory/Meditory/Features/Notification/RoutineNotificationScheduler.swift
노티피케이션 매니저의 빌드경고 해결.
컨커런시의 Sendable관련인거 같아서 엑스코드에서 제안하는 @preconcurrency 매니져 임시 조치
후에 뜨는 userInfo형의 문제를 명시적으로 바꿔서 해결
어떤 변경 사항이 있나요?
> refactor:노티피케이션 매니저 경고 문구 해결(SCRUM-260)

- Meditory/Meditory/Features/AddSupplement/ViewModel/AddSupplementViewModel.swift
- Meditory/Meditory/Features/Notification/RoutineNotificationScheduler.swift
- Meditory/Meditory/Features/Setting/ViewModel/SettingViewModel.swift
- Meditory/Meditory/Features/SupplementDetail/ViewModel/SupplementDetailViewModel.swift
- Meditory/Meditory/MeditoryApp.swift
- Meditory/Meditory/Persistence/ExtraInfo.swift
- Meditory/Meditory/Persistence/Models/Routine/Routine.swift
- Meditory/Meditory/Persistence/Models/Setting/Setting.swift
- Meditory/Meditory/Persistence/Models/User/User.swift
- Meditory/Meditory/Persistence/Models/User/UserExtraInfo.swift
- Meditory/Meditory/Persistence/Models/User/UserLifeStyle.swift
- Meditory/Meditory/Persistence/Models/User/UserProfile.swift
- Meditory/Meditory/Persistence/Models/User/UserStatus.swift
각 모델에 Sendable 추가하였습니다
RoutineNofiticationScheduler의 modelContext를 RoutineStore를 활용하도록 변경하였습니다
어떤 변경 사항이 있나요?
> Sendable 추가 및 RoutineNotificationScheduler modelContext -> Store 변경(SCRUM-261)

- Meditory/Meditory/Features/Recommend/Components/ProductTile.swift
- Meditory/Meditory/Features/Recommend/View Model/NutrientViewModel.swift
- Meditory/Meditory/Features/Recommend/View Model/ProductRecommendViewModel.swift
- Meditory/Meditory/Features/Recommend/View Model/ScoreViewModel.swift
- Meditory/Meditory/Features/Recommend/View Model/SearchDetailViewModel.swift
- Meditory/Meditory/Features/Recommend/View Model/SearchViewModel.swift
- Meditory/Meditory/Features/Recommend/View/AnalysisView.swift
- Meditory/Meditory/Features/Recommend/View/ImageCardView.swift
- Meditory/Meditory/Features/Recommend/View/NutrientCardView.swift
- Meditory/Meditory/Features/Recommend/View/NutrientDetailSectionView.swift
- Meditory/Meditory/Features/Recommend/View/ProductCardView.swift
- Meditory/Meditory/Features/Recommend/View/RecommendNutrientsView.swift
- Meditory/Meditory/Features/Recommend/View/RecommendView.swift
- Meditory/Meditory/Features/Recommend/View/ScoreDetailView.swift
- Meditory/Meditory/Features/Recommend/View/ScoreView.swift
- Meditory/Meditory/Features/Recommend/View/ScrapView.swift
- Meditory/Meditory/Features/Recommend/View/SearchCardView.swift
- Meditory/Meditory/Features/Recommend/View/SearchDetailView.swift
- Meditory/Meditory/Features/Recommend/View/SearchView.swift
- Meditory/Meditory/Features/Recommend/View/WebPage.swift
- Meditory/Meditory/Features/Recommend/View/WebView.swift
- Meditory/Meditory/Network/Core/APIKey.swift
- Meditory/Meditory/Network/Endpoint/SearchEndpoint.swift
- Meditory/Meditory/Network/Extension/CSEImage+Pillyze.swift
- Meditory/Meditory/Resource/Info.plist
- Meditory/MeditoryTests/RecommendViewTest/RecommendViewTests.swift
테스트 코드 작성
프리뷰 주석처리 삭제
전체 코드 컨트롤 + I 
어떤 변경 사항이 있나요?
> Fix/ 영양제 경고 문구 (SCRUM-259)

- Meditory/Meditory/Features/Onboarding/Model/Step.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingView.swift
온보딩 순서를 재배치 했습니다.(정보수집 동의를 맨 앞으로 조절)
어떤 변경 사항이 있나요?
> 온보딩 순서 재배치 (SCRUM-265)

- Meditory/Meditory/Features/Onboarding/Components/ImageWithTitle.swift
- Meditory/Meditory/Features/Onboarding/Components/TitleView.swift
- Meditory/Meditory/Features/Onboarding/Model/Prompt.swift
- Meditory/Meditory/Features/Onboarding/View/OnboardingGenderView.swift
타이틀의 이름이 길 경우 텍스트가 계속 늘어나는 현상을 고쳤습니다
어떤 변경 사항이 있나요?
> 온보딩 타이틀 길이 이슈 해결(SCRUM-267)
